### ISSUE TITLE
[BUG] Unexpected exception while loading graph

### ISSUE THREAD

**Issue by SPCPA** [forcedotcom/sfdx-scanner#1207]
**Describe the bug**
We are trying to run this command line:
 sfdx scanner:run:dfa --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./" --category="Security"

**To Reproduce**
Hard to reproduce without our repo.

**Expected behavior**
While the tool is loading file in the logs (see logs below) we are getting this exception.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Scanner Version [e.g. 22]  @salesforce/sfdx-scanner 3.16.0 / @salesforce/cli/2.10.2 win32-x64 node-v18.15.0

**Additional context**

2023-10-03 09:10:11  INFO  GraphUtil:207 - Loading file. path=C:\Users\TRIGGER.trigger
2023-10-03 09:10:11  INFO  GraphUtil:244 - Skipping subtree of path=C:\Users\PROJECT\node_modules
2023-10-03 09:11:15  ERROR Main:156 - Unexpected exception while loading graph
com.salesforce.exception.UnexpectedException: vertex=ArrayLoadExpression{DefiningType=SObjectManager, BeginLine=513, EndLine=513}, labels=[Ljava.lang.String;@4497fcd9
	at com.salesforce.graph.build.MethodPathBuilderVisitor.assertVertexLabel(MethodPathBuilderVisitor.java:638) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor.visitSwitchStatement(MethodPathBuilderVisitor.java:436) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:140) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor.apply(MethodPathBuilderVisitor.java:97) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.afterInsert(AbstractApexVertexBuilder.java:119) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:103) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:99) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:35) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.CustomerApexVertexBuilder.build(CustomerApexVertexBuilder.java:21) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.Util.buildGraph(Util.java:39) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.GraphUtil.loadSourceFolders(GraphUtil.java:170) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main$Dependencies.loadSourceFoldersToGraph(Main.java:247) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.execute(Main.java:150) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.process(Main.java:100) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.main(Main.java:68) [sfge-1.0.1-pilot.jar:?]

Thanks

**Comment by jfeingold35** [comment]
What is happening at `SObjectManager.cls`, line 513?

**Comment by SPCPA** [comment]
Hello @jfeingold35,

Here is the snippet of code:
`when MULTIPICKLIST {
					if(value.contains(CONSTANTS.KEY_SEPARATOR)){
						List<String> splitedValues = value.split(CONSTANTS.KEY_SEPARATOR);

						switch on splitedValues[0] {`
on 513 is the switch.

Thanks

**Comment by SPCPA** [comment]
Hello,
I just wanted to add a side note that if I comment the 2nd switch within the first switch it is working. 
Thanks

**Comment by jfeingold35** [comment]
@SPCPA , unfortunately, no. We apologize, but the team's bandwidth has been pretty narrow for the past few releases, and we haven't had time to address this one. We appreciate your patience in the meatime.

**Comment by nikhil-mittal-165** [comment]
Thank you for taking the time to report this! We're currently doing some maintenance and closing out older pre-v5 issues. We highly recommend upgrading to Code Analyzer v5. If the problem persists after upgrading, please open a new ticket, we'd love to help you sort it out!
