### ISSUE TITLE
[BUG] NoSuchElementException: No value present error when passing describe to method

### ISSUE THREAD

**Issue by simon-nc-squared** [forcedotcom/sfdx-scanner#1247]
**Description:**
When running the DFA scanner against our codebase we are getting a `NoSuchElementException: No value present` exception. I've narrowed it down to when we pass a describe to a method. This is similar to https://github.com/forcedotcom/sfdx-scanner/issues/1209 so could be a duplicate.

**Documentation:**
```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?]
	at com.salesforce.rules.fls.apex.operations.ObjectBasedCheckUtil.isCrudCheckExpected(ObjectBasedCheckUtil.java:67) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.fls.apex.operations.SchemaBasedValidationAnalyzer.isCheckLevelValid(SchemaBasedValidationAnalyzer.java:199) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.fls.apex.operations.SchemaBasedValidationAnalyzer.convert(SchemaBasedValidationAnalyzer.java:174) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.fls.apex.operations.SchemaBasedValidationAnalyzer.checkForValidation(SchemaBasedValidationAnalyzer.java:77) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.fls.apex.operations.FlsValidationCentral.checkSchemaBasedFlsValidation(FlsValidationCentral.java:71)
```
[sfge.log](https://github.com/forcedotcom/sfdx-scanner/files/13438149/sfge.log)

**Steps To Reproduce:**
Run the DFA scanner against the following code. `testFails` will fail with the `NoSuchElementException` error and `testWorks` will correctly report a FLS violation.
```
public with sharing class OptionalIssue {

    @RemoteAction @ReadOnly
    public static void testFails(Account acct) {
        DescribeSObjectResult describe = acct.getSObjectType().getDescribe();
        if (canInsertDescribe(describe)) {
            doInsert(acct);
        }
    }

    @RemoteAction @ReadOnly
    public static void testWorks(Account acct) {
        if (canInsertObject(acct)) {
            doInsert(acct);
        }
    }
    
    public static Boolean canInsertDescribe(DescribeSObjectResult describe) {
        if (describe.isCreateable()) {
            return true;
        }
        return false;
    }
    
    public static Boolean canInsertObject(Account acct) {
        if (acct.getSObjectType().getDescribe().isCreateable()) {
            return true;
        }
        return false;
    }
    
    public static void doInsert(Account acct) {
        Database.insert(acct);
    }
}
```

**Expected Behaviour:**
For the scan to correctly report the FLS error for both methods.

**Desktop:**
- Operating System. Example: Windows 10
- Code Analyzer version. Example: v3.18.0
- Salesforce CLI version. Example: @salesforce/cli/2.16.8

**Comment by rmohan20** [comment]
Duplicate of #1209

**Comment by nikhil-mittal-165** [comment]
Thank you for taking the time to report this! We're currently doing some maintenance and closing out older pre-v5 issues. We highly recommend upgrading to Code Analyzer v5. If the problem persists after upgrading, please open a new ticket, we'd love to help you sort it out!
