### ISSUE TITLE
[BUG] Exception in retirejs engine of latest beta scanner

### ISSUE THREAD

**Issue by rtoepfer** [forcedotcom/sfdx-scanner#1469]
Running Security Scan
 ›   Warning: Plugin @salesforce/sfdx-scanner (4.1.0) differs from the version 
 ›   specified by sf (3.24.0)
Warning: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
/home/vsts/.local/share/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/retire-js/RetireJsEngine.js:248
            throw new core_1.SfError(message);
            ^

SfError: Cannot read properties of undefined (reading 'map')
    at RetireJsEngine.processOutput (/home/vsts/.local/share/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/retire-js/RetireJsEngine.js:248:19)
    at ChildProcess.<anonymous> (/home/vsts/.local/share/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/retire-js/RetireJsEngine.js:171:30)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  cause: undefined,
  actions: undefined,
  exitCode: 1
}

### `scanner run` Issue Template

Fill out this template to submit your Code Analyzer issue.

**Description**:

**Documentation**:

**Steps To Reproduce**:

**Expected Behavior**:

**Screenshots**:

**Desktop**:

**Additional Context**:

**Workaround**:

**Urgency**:

**Comment by johnbelosf** [comment]
@rtoepfer can you please fill in the above template? Otherwise unfortunately we'll need to close this issue

**Comment by stephen-carter-at-sf** [comment]
What is the output
sf --version
on your machine?

**Comment by stephen-carter-at-sf** [comment]
Closing issue since no response has been provided and the template was not filled out.
