### ISSUE TITLE
apex.jorje.parser.impl.BaseApexLexer dedupe

### ISSUE THREAD

**Issue by suryansh-gupta** [forcedotcom/sfdx-scanner#779]
**Describe the bug**
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075528 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 8 ms.
**To Reproduce**
sfdx scanner:run:dfa --target './force-app/main/default/classes' --projectdir './force-app/main/default' --format csv
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83838557/181358712-688824a9-b78f-48bd-8b64-ac7c3f960a69.png)

**Desktop (please complete the following information):**
 - Scanner Version [e.g. 22]

**Additional context**

apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075528 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 8 ms.
Exception in thread "main" com.salesforce.exception.UserActionException: Please remove unreachable code to proceed with analysis:
at com.salesforce.graph.build.MethodPathBuilderVisitor.addEdge(MethodPathBuilderVisitor.java:599)
        at com.salesforce.graph.build.MethodPathBuilderVisitor.addEdgeFromPreviousSibling(MethodPathBuilderVisitor.java:591)
        at com.salesforce.graph.build.MethodPathBuilderVisitor.visit(MethodPathBuilderVisitor.java:178)
        at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:150)
        at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159)
        at com.salesforce.graph.build.MethodPathBuilderVisitor.apply(MethodPathBuilderVisitor.java:97)
        at com.salesforce.graph.build.AbstractApexVertexBuilder.afterInsert(AbstractApexVertexBuilder.java:119)
        at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:103)
        at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:99)
        at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:35)
        at com.salesforce.graph.build.CustomerApexVertexBuilder.build(CustomerApexVertexBuilder.java:21)
        at com.salesforce.graph.build.Util.buildGraph(Util.java:39)
        at com.salesforce.graph.ops.GraphUtil.loadSourceFolders(GraphUtil.java:158)
        at com.salesforce.Main.execute(Main.java:128)
        at com.salesforce.Main.process(Main.java:81)
        at com.salesforce.Main.main(Main.java:60)

**Comment by rmohan20** [comment]
Hi @suryansh-gupta - thanks for reporting this issue.

Amongst other noise, this is the message on the exception that SFGE is trying to convey:
```
Please remove unreachable code to proceed with analysis: <file_location and line number>
```
There's possibly an unreachable line of code (such as a statement after a `return` or `throw` statement) that needs to be removed so that SFGE can continue building paths. Please let us know if this is not the case.

We have a fix coming up in the next minor release that should help display this kind of error better. We'll also follow up on the `Deduped array ApexLexer.DFA22_transition` info log and check if we can hide it.

**Comment by rmohan20** [comment]
The latest 3.4.0 version has related fixes. Closing this issue. Please let us know if it persists. Thanks.
