### ISSUE TITLE
[BUG] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by jduelfer** [forcedotcom/sfdx-scanner#825]
**Describe the bug**
When trying to run `sfdx scanner:run:dfa --target <my_class.cls>` on a global class that makes an HTTP Callout, I get the following error:
```
2022-09-14 13:49:17  ERROR Main:152 - Error while running rules
com.salesforce.rules.ThreadableRuleExecutor$ThreadableRuleExecutorException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
	at com.salesforce.rules.ThreadableRuleExecutor.waitForCallable(ThreadableRuleExecutor.java:111) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.ThreadableRuleExecutor.run(ThreadableRuleExecutor.java:51) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.AbstractRuleRunner.runPathBasedRules(AbstractRuleRunner.java:99) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.AbstractRuleRunner.runRules(AbstractRuleRunner.java:48) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.execute(Main.java:149) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.process(Main.java:83) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.main(Main.java:62) [sfge-1.0.1-pilot.jar:?]
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1011) ~[?:?]
	at com.salesforce.rules.ThreadableRuleExecutor.waitForCallable(ThreadableRuleExecutor.java:109) ~[sfge-1.0.1-pilot.jar:?]
	... 6 more
Caused by: java.lang.OutOfMemoryError
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:608) ~[?:?]
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1011) ~[?:?]
	at com.salesforce.rules.ThreadableRuleExecutor.waitForCallable(ThreadableRuleExecutor.java:109) ~[sfge-1.0.1-pilot.jar:?]
	... 6 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.newNode(HashMap.java:1888) ~[?:?]
	at java.util.HashMap.putVal(HashMap.java:631) ~[?:?]
	at java.util.HashMap.put(HashMap.java:612) ~[?:?]
	at com.salesforce.graph.ops.CloneUtil.cloneMap(CloneUtil.java:188) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.CloneUtil.cloneHashMap(CloneUtil.java:129) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpander.<init>(ApexPathExpander.java:267) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpanderUtil.getForkedExpanders(ApexPathExpanderUtil.java:325) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpanderUtil.expand(ApexPathExpanderUtil.java:264) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpanderUtil.expand(ApexPathExpanderUtil.java:154) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpanderUtil._expand(ApexPathExpanderUtil.java:88) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpanderUtil.expand(ApexPathExpanderUtil.java:58) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.ApexPathUtil.getPaths(ApexPathUtil.java:188) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.ApexPathUtil.getForwardPaths(ApexPathUtil.java:70) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.PathBasedRuleRunner.getPaths(PathBasedRuleRunner.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.PathBasedRuleRunner.runRules(PathBasedRuleRunner.java:54) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.ThreadableRuleExecutor$CallableExecutor.call(ThreadableRuleExecutor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.ThreadableRuleExecutor$CallableExecutor.call(ThreadableRuleExecutor.java:115) ~[sfge-1.0.1-pilot.jar:?]
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1458) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:413) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:741) ~[?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1466) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

**To Reproduce**
Create a global class that makes an HTTP Callout to an external system. Running `sfdx scanner:run --target <my_class.cls>` using PMD (i.e. not adding the `dfa` suffix) should only return the one _Best Practices_ rule violation for avoiding global modifiers. No other violations are found by the previous version of the scanner.

Then, run `sfdx scanner:run:dfa --target <my_class.cls>` specifying the new Graph Engine. After running for ~5 minutes, the error above is written to the logs.

**Expected behavior**
I would expect to be able to run the scanner on files that had next-to-no rule violations in the previous 2.x version.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bit
 - Scanner Version 3.4.0
 - Java versions attempted (specifying the `javaHome` variable in `Config-pilot.json`):
   - OpenJDK jdk-16.0.1
   - Amazon Corretto jdk11.0.11_9

**Additional context**
* "Workaround": None
* "Urgency": Not business-stopping - I would like to be able to run the scanner on all my classes, but this error is preventing me from doing so.
* Note that although this happens on this specific class which makes a callout, I have seen this error run on other classes. Trying to run `sfdx scanner:run:dfa` without specifying a `--target` produces a number of errors.

**Comment by jfeingold35** [comment]
Hi @jduelfer .
We're aware of issues with the DFA engine running out of memory, and our documentation includes some [potential troubleshooting steps](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/working-with-sfge/#outofmemory-java-heap-space-error). Have you already tried those?
Thanks!

**Comment by jfeingold35** [comment]
We apparently fixed this one a while ago and never closed it, so we're closing it now.
