### ISSUE TITLE
[BUG] Unexpected exception for switch with cast variable

### ISSUE THREAD

**Issue by tprouvot** [forcedotcom/sfdx-scanner#886]
**Describe the bug**
Hi team,
When running the command `sfdx scanner:run:dfa -p force-app -o test.html -t "force-app/main/default/classes/*.cls"` I met the following error:

"ERROR Main:154 - Unexpected exception while loading graph"

It seems to be linked to the usage of a switch with a dynamic cast variable:
`switch on (String)iter {` met in the following class [sfpegMerge_CTL](https://github.com/tprouvot/PEG_LIST/blob/master/force-app/main/default/classes/sfpegMerge_CTL.cls#L81)

**To Reproduce**
Clone the repo https://github.com/tprouvot/PEG_LIST/
Execute the command `sfdx scanner:run:dfa -p force-app -o test.html -t "force-app/main/default/classes/*.cls"`

**Expected behavior**
No errors since the apex class compiles and is deployed without error.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Scanner Version 3.6.2

**Additional context**

``` lgt
2022-11-16 10:33:15  ERROR Main:154 - Unexpected exception while loading graph
com.salesforce.exception.UnexpectedException: vertex=CastExpression{DefiningType=sfpegMerge_CTL, BeginLine=81, EndLine=81}, labels=[Ljava.lang.String;@43b172e3
	at com.salesforce.graph.build.MethodPathBuilderVisitor.assertVertexLabel(MethodPathBuilderVisitor.java:638) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor.visitSwitchStatement(MethodPathBuilderVisitor.java:436) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:140) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor.apply(MethodPathBuilderVisitor.java:97) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.afterInsert(AbstractApexVertexBuilder.java:119) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:103) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:99) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:35) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.CustomerApexVertexBuilder.build(CustomerApexVertexBuilder.java:21) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.Util.buildGraph(Util.java:39) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.GraphUtil.loadSourceFolders(GraphUtil.java:168) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main$Dependencies.loadSourceFoldersToGraph(Main.java:245) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.execute(Main.java:148) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.process(Main.java:102) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.main(Main.java:71) [sfge-1.0.1-pilot.jar:?]
```
I'm a Salesforce employee so you can reach me on Slack if you need more information.

"Workaround": Have you found any ways to sidestep the problem?
If we remove the dynamic casting of the variable, there's no more errors

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".
Not business-stopping

**Comment by rmohan20** [comment]
Hi @tprouvot - thanks for letting us know. We'll schedule a fix for this bug in one of our upcoming patch releases.

**Comment by nikhil-mittal-165** [comment]
Thank you for taking the time to report this! We're currently doing some maintenance and closing out older pre-v5 issues. We highly recommend upgrading to Code Analyzer v5. If the problem persists after upgrading, please open a new ticket, we'd love to help you sort it out!
