### ISSUE TITLE
[BUG] vertex=ArrayLoadExpression{DefiningType=

### ISSUE THREAD

**Issue by Olchawa** [forcedotcom/sfdx-scanner#973]
Hey, I am getting unexpected exception thrown for the following code.

com.salesforce.exception.UnexpectedException: vertex=ArrayLoadExpression{DefiningType=SharingSetupManager, BeginLine=7, EndLine=7}, labels=[Ljava.lang.String;@3a70acd5
	at com.salesforce.graph.build.MethodPathBuilderVisitor.assertVertexLabel(MethodPathBuilderVisitor.java:638) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor.visitSwitchStatement(MethodPathBuilderVisitor.java:436) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:140) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor.apply(MethodPathBuilderVisitor.java:97) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.afterInsert(AbstractApexVertexBuilder.java:119) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:103) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:99) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:35) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.CustomerApexVertexBuilder.build(CustomerApexVertexBuilder.java:21) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.Util.buildGraph(Util.java:39) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.GraphUtil.loadSourceFolders(GraphUtil.java:168) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main$Dependencies.loadSourceFoldersToGraph(Main.java:246) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.execute(Main.java:149) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.process(Main.java:99) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.main(Main.java:68) [sfge-1.0.1-pilot.jar:?]

and code:
![Zrzut ekranu 2023-02-15 o 10 16 17](https://user-images.githubusercontent.com/26882113/218985071-538a625c-f9d9-411a-ad7d-be9055e31484.png)

**Comment by rmohan20** [comment]
Hi @Olchawa - thanks for letting us know. You've found a new bug for us - we'll fix this.
In the meantime, could you extract `lstInputRecords[0]` to a new variable and use the variable in the switch statement? That could temporarily workaround the issue. Please let us know if it helps you get past this error.

**Comment by nikhil-mittal-165** [comment]
Thank you for taking the time to report this! We're currently doing some maintenance and closing out older pre-v5 issues. We highly recommend upgrading to Code Analyzer v5. If the problem persists after upgrading, please open a new ticket, we'd love to help you sort it out!
